entryPoints:
  web:
    address: ":8181"
  websecure:
    address: ":443"

providers:
  file:
    directory: "/config"
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: traefik
    watch: true
    exposedByDefault: false

certificatesResolvers:
  lets-encrypt:
    acme:
      email: yourname@example.com
      storage: /acme.json
      httpChallenge:
        entryPoint: web 
